### ISSUE TITLE
[13pt] Errors from processing 12030105

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#127]
Using the branch of dev-depth-grid-rounding PR [1pt] Fixed rounding issue for meters for rating curves [#124](https://github.com/NOAA-OWP/ras2fim/pull/124 which had 108 models to process, four errors were recorded. No resesarch has yet been done.

	
	+++++++ Processing for code  STEP 5 +++++++
	
	+=================================================================+
	|                NWM RASTER LIBRARY FROM HEC-RAS                  |
	+-----------------------------------------------------------------+
	  ---(w) HUC-8 WATERSHED: 12030105
	  ---(i) INPUT PATH: c:\ras2fim_data\output_ras2fim\12030105_2276_230802\02_shapes_from_conflation
	  ---(o) OUTPUT PATH: c:\ras2fim_data\output_ras2fim\12030105_2276_230802\05_hecras_output
	  ---(p) PROJECTION PATH: c:\ras2fim_data\output_ras2fim\12030105_2276_230802\02_shapes_from_conflation\12030105_huc_12_ar.prj
	  ---(t) TERRAIN PATH: c:\ras2fim_data\output_ras2fim\12030105_2276_230802\04_hecras_terrain
	  ---[s]   Optional: Standard Input Path: C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src
	  ---[z]   Optional: Output Elevation Step: 0.5
	  ---[c]   Optional: Terrain Check Only: False
	===================================================================
	******************* of 30): |███████████----------------| 43% Complete
	Error:
	   str_feature_id = 1262797
	(-2147352567, 'Exception occurred.', (0, 'RAS60', 'Subscript out of range', None, 1000009, -2146828279), None)
	   Traceback (most recent call last):
	  File "C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src\worker_fim_rasters.py", line 1195, in fn_main_hecras
	    river = fn_create_hecras_files(str_feature_id, str_geom_path, flt_ds_xs, flt_us_xs, int_max_q, str_hecras_path_to_create, tpl_settings)
	  File "C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src\worker_fim_rasters.py", line 1128, in fn_create_hecras_files
	    fn_run_hecras(str_ras_projectpath, int_max_flow, model_unit, tpl_settings)
	  File "C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src\worker_fim_rasters.py", line 581, in fn_run_hecras
	    arr_max_depth[int_count_nodes], v1, v2, v3, v4, v5, v6 = hec.Output_NodeOutput(RivID, RchID, i+1, 0, int_prof+1, int_max_depth_id)
	  File "<COMObject RAS60.HECRASController>", line 3, in Output_NodeOutput
	  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
	    result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
	pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'RAS60', 'Subscript out of range', None, 1000009, -2146828279), None)
	
	   for more details.. see the 05_hecras_output / errors_found.log
	*******************
	******************* of 30): |██████████████████████████-| 97% Complete
	Error:
	   str_feature_id = 1260349
	(-2147352567, 'Exception occurred.', (0, 'RAS60', 'Subscript out of range', None, 1000009, -2146828279), None)
	   Traceback (most recent call last):
	  File "C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src\worker_fim_rasters.py", line 1195, in fn_main_hecras
	    river = fn_create_hecras_files(str_feature_id, str_geom_path, flt_ds_xs, flt_us_xs, int_max_q, str_hecras_path_to_create, tpl_settings)
	  File "C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src\worker_fim_rasters.py", line 1128, in fn_create_hecras_files
	    fn_run_hecras(str_ras_projectpath, int_max_flow, model_unit, tpl_settings)
	  File "C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src\worker_fim_rasters.py", line 581, in fn_run_hecras
	    arr_max_depth[int_count_nodes], v1, v2, v3, v4, v5, v6 = hec.Output_NodeOutput(RivID, RchID, i+1, 0, int_prof+1, int_max_depth_id)
	  File "<COMObject RAS60.HECRASController>", line 3, in Output_NodeOutput
	  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
	    result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
	pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'RAS60', 'Subscript out of range', None, 1000009, -2146828279), None)
	
	   for more details.. see the 05_hecras_output / errors_found.log
	*******************
	*******************
	Error:
	   str_feature_id = 1260347
	(-2147352567, 'Exception occurred.', (0, 'RAS60', 'Subscript out of range', None, 1000009, -2146828279), None)
	   Traceback (most recent call last):
	  File "C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src\worker_fim_rasters.py", line 1195, in fn_main_hecras
	    river = fn_create_hecras_files(str_feature_id, str_geom_path, flt_ds_xs, flt_us_xs, int_max_q, str_hecras_path_to_create, tpl_settings)
	  File "C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src\worker_fim_rasters.py", line 1128, in fn_create_hecras_files
	    fn_run_hecras(str_ras_projectpath, int_max_flow, model_unit, tpl_settings)
	  File "C:\Users\rdp-user\Projects\dev-depth-grid-rounding\ras2fim\src\worker_fim_rasters.py", line 581, in fn_run_hecras
	    arr_max_depth[int_count_nodes], v1, v2, v3, v4, v5, v6 = hec.Output_NodeOutput(RivID, RchID, i+1, 0, int_prof+1, int_max_depth_id)
	  File "<COMObject RAS60.HECRASController>", line 3, in Output_NodeOutput
	  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
	    result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
	pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'RAS60', 'Subscript out of range', None, 1000009, -2146828279), None)
	
	   for more details.. see the 05_hecras_output / errors_found.log
	*******************
	Processing HUCs (30 of 30): |███████████████████████████| 100% Complete

**Comment by RobHanna-NOAA** [comment]
Closed.  Duplicate to [#133 ](https://github.com/NOAA-OWP/ras2fim/issues/133)
