### ISSUE TITLE
[1pt] TypeError: iteration over a 0-d array

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/ras2fim#13]
A TypeError occurs in at least one of the HUCs from the IFC dataset. For example, 07080107 from USACE.

**Comment by JamesColl-NOAA** [comment]
More explicit error:
```
+=================================================================+
|    STREAM AND CROSS SECTION SHAPEFILES FROM HEC-RAS DIRECTORY   |
|     Created by Andy Carter, PE of the National Water Center     |
+-----------------------------------------------------------------+
  ---(i) INPUT PATH: B:\<PATH>\07080107_USACE
  ---(o) OUTPUT PATH: B:\<PATH>\01_shapes_from_hecras
  ---(p) MODEL PROJECTION: EPSG:26915
+-----------------------------------------------------------------+
Traceback (most recent call last):--------------| 25.0% Complete
  File "ras2fim.py", line 329, in <module>
    fn_run_ras2fim(str_huc8_arg,
  File "ras2fim.py", line 103, in fn_run_ras2fim
    fn_create_shapes_from_hecras(str_ras_path_arg,
  File "B:\<PATH>\ras2fim\src\create_shapes_from_hecras.py", line 670, in fn_create_shapes_from_hecras
    gdf_return_stream = fn_geodataframe_stream_centerline(ras_path, STR_CRS_MODEL)
  File "B:\<PATH>\ras2fim\src\create_shapes_from_hecras.py", line 299, in fn_geodataframe_stream_centerline
    for row in n2:
TypeError: iteration over a 0-d array
```
