### ISSUE TITLE
[3pt] MultiLineString object is not iterable error

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#167]
During a full huc test against 12040101, it triggered an error of:

Traceback (most recent call last):
  File "ras2fim.py", line 723, in <module>
    init_and_run_ras2fim(**args)
  File "ras2fim.py", line 182, in init_and_run_ras2fim
    fn_run_ras2fim(
  File "ras2fim.py", line 265, in fn_run_ras2fim
    fn_conflate_hecras_to_nwm(
  File "C:\Users\rdp-user\Projects\ras2fim-dev\ras2fim\src\conflate_hecras_to_nwm.py", line 315, in fn_conflate_hecras_to_nwm
    for shp_line in shp_geom:
TypeError: 'MultiLineString' object is not iterable

**Comment by RobHanna-NOAA** [comment]
Showed up against 12040101 but not 12030105 .  There are a number of things that suggest that there are some bad models in 12040101, but we will address those separately. This card will focus on this fix only.
