### ISSUE TITLE
[8pt] Critical error HEC-RAS subscript out of range

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#189]
During some testing with the new logging system, one feature ID triggered an HEC-RAS win32 error. While this appears to affect only one HUC (12030106) and one feature (1293170 / 3 models), it is an error that can likely be fixed easily. Reviewing the args being passed into the HEC-RAS engine can be reviewed and see if we skip the attempt to submit it to the HEC-RAS engine in the first place.

Details:
023-10-25 00:59:40 (DEBUG   ) || Starting processing for feature id: 1293170
	2023-10-25 00:59:40 (DEBUG   ) || str_path_to_create is c:\ras2fim_data\output_ras2fim\12030106_2276_231025\05_hecras_output\HUC_120301060503\1293170
	2023-10-25 00:59:41 (CRITICAL) || ++++++++++++++++++++++++
	2023-10-25 00:59:41 (CRITICAL) || An exception occurred with the HEC-RAS engine or its parameters.
	2023-10-25 00:59:41 (CRITICAL) || str_ras_projectpath is c:\ras2fim_data\output_ras2fim\12030106_2276_231025\05_hecras_output\HUC_120301060503\1293170\HEC-RAS\1293170.prj
	2023-10-25 00:59:41 (CRITICAL) || Traceback (most recent call last):
	  File "C:\Users\rdp-user\Projects\dev-logging\ras2fim\src\worker_fim_rasters.py", line 686, in fn_run_hecras
	    (arr_max_depth[int_count_nodes], v1, v2, v3, v4, v5, v6) = hec.Output_NodeOutput(
	  File "<COMObject RAS630.HECRASController>", line 3, in Output_NodeOutput
	  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\win32com\client\dynamic.py", line 368, in _ApplyTypes_
	    result = self._oleobj_.InvokeTypes(
	pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'RAS630', 'Subscript out of range', None, 1000009, -2146828279), None)

Update: it is happening to c:\ras2fim_data\output_ras2fim\12030106_2276_231025\05_hecras_output\HUC_120301060502\1293148\HEC-RAS\1293148.prj as well.

**Comment by RobHanna-NOAA** [comment]
Closed. Duplicate of [issue 133](https://github.com/NOAA-OWP/ras2fim/issues/133).
